fix(Discount): remove discount in Subscription GalaxPay
ecomplus/app-galaxpay pull request #31
Opened 2022-07-05 14:08 UTC by wisley7l

Relacionado a issue #28

2022-07-09 23:28 UTC, leomp12 requested changes
E tá dando muito erro do StandardJS, como a diff é grande é bom passar o linter direitinho 😄 
Nesse repo (e outros parecidos) desabilita a extensão do ESLint e habilta o _StandardJS - JavaScript Standard Style_

2022-07-09 23:28 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +          const itemsOrder = response.data.items
Por que tá lendo o pedido se isso vem nos `params`? 🤔 
Por exemplo aí https://github.com/ecomplus/app-pagarme/blob/master/functions/routes/ecom/modules/create-transaction.js#L13 e https://github.com/ecomplus/app-pagarme/blob/master/functions/routes/ecom/modules/create-transaction.js#L145-L155
O schema do obejo `params` aí https://apx-mods.e-com.plus/api/v1/create_transaction/schema.json?store_id=100

2022-07-11 11:25 UTC, wisley7l commented on functions/routes/ecom/modules/create-transaction.js
> +          const itemsOrder = response.data.items
A ideia aqui é capturar os itens que são brindes, para que não sejam contabilizados no calculo do plano de desconto da recorrência. Os itens que são brindes estava indentificando-os atraves das `flags`.

2022-07-11 22:50 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +          const itemsOrder = response.data.items
De qualquer forma ter que ler o pedido aí abre precedente pra quebrar a transação, não acho que seja uma boa ideia de qualquer forma, se realmente não tiver como identificar os brindes pelo `params.items` (🤔) teremos que implementar isso de outra forma depois

2022-07-13 17:20 UTC, wisley7l commented
> https://apx-mods.e-com.plus/api/v1/create_transaction/schema.json?store_id=100
O `params.items` aqui realmente não tem a propriedade `flags` e também a `amout.balance` também não. Acredito que essas sejam as únicas pendências.

2022-07-13 18:37 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +    galaxpaySubscriptions.Transactions = [fristTransaction]
Só com isso aqui ele já vai criar uma transação diferente pro primeiro pagamento? 😮

2022-07-13 18:53 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
> +                    }
Só podemos tirar o brinde se você reduzir o respectivo valor na cobrança da assinatura

2022-07-15 00:58 UTC, leomp12 commented on functions/lib/galaxpay/update-subscription.js
> +      items.splice(i, 1)
Na real isso nem é necessário porque c não usa mais o array de items...

2022-07-15 00:58 UTC, leomp12 commented on functions/lib/galaxpay/update-subscription.js
> +  amount.total = amount.subtotal + (amount.tax || 0) + (amount.freight || 0) + (amount.extra || 0)
Você tá mexendo no `amount` e `items` por referência, não precisava e não é o ideal mas tudo bem, desde que não se confunda e não use eles em nenhum lugar fora da função depois... tá usando não né?

2022-07-15 00:58 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
> +
Uai mas por que tá tratando isso aqui E na função `updateValueSubscription`?

2022-07-15 11:56 UTC, wisley7l commented on functions/routes/galaxpay/webhooks.js
> +
Aqui é quando criamos os pedidos na _**E-com**_, como por exemplo o 2º pedido da recorrência. 
Já a  `updateValueSubscription` faz o recálculo para atualizar o valor da assinatura no GalaxPay

2022-07-15 22:28 UTC, leomp12 approved these changes
boa nelson 👍🏾

2022-07-15 22:28 UTC, merged