refactor(webhooks): Fix canceled payment errors, variable and function names
ecomplus/app-galaxpay pull request #47
Opened 2023-02-15 22:09 UTC by wisley7l

Referente ao #45

2023-02-18 16:07 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
>                }
Não deveria ser o contrário aqui?
Primeiro você vê se o valor muda (a.k.a.: existe algum brinde ou outro desconto de primeira compra no pedido), se não mudar você não faz nada disso, nem busca nada no Firestore, menos ainda envia uma alteração no Galaxpay.
Quando você atualiza o valor no Firestore, é pra quê? Aliás tem algum motivo pra salva o valor do pedido no Firestore? 😄

2023-02-18 16:07 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
> +          } else {
O authorized não pode vir com antecedência? Acho que os pedidos de períodos consecutivos deveriam ser criados quando _pago_ apenas, não?
A não ser que você verifique que a data é correspondente ao período do plano, por exemplo, se a assinatura é de 1 mês e a data do webhook é de fato 1 mês após o último pedido, você cria o novo pedido mesmo que o status não seja pago.

2023-02-24 20:40 UTC, wisley7l commented on functions/routes/galaxpay/webhooks.js
>                }
Valor é salvo para verificar quando há mudança no pedido original (Troca de pedidos), comparar o valor anterior com valor atual.

2023-02-25 03:11 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
>                }
Então, mas se você você já tem o valor salvo você não acha que deveria verificar ele antes? E daí se não houver mudança você não atualizada nada no pedido (requests a menos).

2023-02-25 03:12 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
>                }
Talvez seja um problema com nomenclatura, mas supondo que seu método `updateValueSubscription` atualiza o valor da assinatura, acho que ele não deveria ser chamado se você souber que o valor atual é igual ao valor anterior (= não há o que alterar)

2023-02-28 15:08 UTC, leomp12 commented on functions/lib/galaxpay/parse-to-ecom.js
>  }
Isso aqui tá exageradamente complexo e na prática também é icorreto 🙃

2023-02-28 15:32 UTC, leomp12 requested changes

2023-02-28 15:32 UTC, leomp12 commented on functions/lib/galaxpay/parse-to-ecom.js
>  }
O que você fez aqui é a mesma coisa de `return id.toString().padStart(24, '0')` , a sintaxe seria bem mais simples e não precisaria criar um array pra depois parsear de volta pra string...
Mas de qualquer forma os dois estão errados 😄

2023-02-28 15:32 UTC, leomp12 commented on functions/lib/galaxpay/parse-to-ecom.js
>  }
Correto seria [`padEnd`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd), não queremos que o ID comece com vários zeros.
Ou só use https://developers.e-com.plus/utils/ecomUtils.html#.randomObjectId

2023-02-28 15:32 UTC, leomp12 commented on functions/lib/store-api/utils.js
> +const createNewOrder = async (appSdk, storeId, auth, originalOrder, galaxPayTransaction, galaxPaySubscription, subscriptionDoc) => {
Ou então você remove o `return new Promise...` e usa await em vez disso, async function com return Promise não faz muito sentido

2023-02-28 15:32 UTC, leomp12 commented on functions/lib/store-api/utils.js
> +const createNewOrder = async (appSdk, storeId, auth, originalOrder, galaxPayTransaction, galaxPaySubscription, subscriptionDoc) => {
Quer dizer, a função do async/await é exatamente uma opção de sintaxe pra não encapsular nested promises (que em geral nem é um problema também)

2023-02-28 15:32 UTC, leomp12 commented on functions/lib/store-api/utils.js
> +const findOrderByTid = async (appSdk, storeId, auth, tid) => {
```suggestion
const findOrderByTid = (appSdk, storeId, auth, tid) => {
```

2023-02-28 15:32 UTC, leomp12 commented on functions/lib/store-api/utils.js
> +const findOrderById = async (appSdk, storeId, auth, orderId) => {
```suggestion
const findOrderById = (appSdk, storeId, auth, orderId) => {
```

2023-02-28 15:32 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
> +  const metadataStoreId = webhookSubscription.ExtraFields.find(metadata => metadata.tagName === 'store_id')
```suggestion
  const type = body?.event
  if (!type) {
    return res.sendStatus(400)
  }
  // const { Transaction, Subscription } = body
  const webhookTransaction = body.Transaction
  const webhookSubscription = body.Subscription
  const galaxpaySubscriptionId = webhookSubscription?.myId
  if (!galaxpaySubscriptionId) {
    return res.sendStatus(400)
  }
  const metadataStoreId = webhookSubscription.ExtraFields?.find(metadata => metadata.tagName === 'store_id')
```

Só pra evitar (pelo menos um pouco) fatal com corpo inválido (a.k.a. se uma pessoa ou bot enviar um POST qualquer nesse endpoint)

2023-02-28 15:32 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
> -    console.log('> ', galaxpayHook.confirmHash)
Isso aqui tinha que ser checado né?

2023-02-28 15:32 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
> -    console.log('> ', galaxpayHook.confirmHash)
Ou você checa isso o hash do webhook, ou você descarta o status que recebeu no corpo (não acredita), nesse segundo caso você precisa ler a assinatura/transação no Galaxpay pra pegar o status atual validado

2023-02-28 15:32 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
> +          status: parseStatus(webhookTransaction.status),
🔓

2023-03-01 00:19 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
>    const metadataStoreId = webhookSubscription.ExtraFields.find(metadata => metadata.tagName === 'store_id')
Então, vou linkar de novo o mesmo comentário:
https://github.com/ecomplus/app-galaxpay/pull/47#discussion_r1120255506
🙃

2023-03-01 00:19 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
>    const metadataStoreId = webhookSubscription.ExtraFields.find(metadata => metadata.tagName === 'store_id')
Aqui optional chain faz diferença... não sabemos ainda se `webhookSubscription` é udefined, depois não sabemos se `webhookSubscription.ExtraFields` é undefined...

2023-03-01 00:19 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
>    const metadataStoreId = webhookSubscription.ExtraFields.find(metadata => metadata.tagName === 'store_id')
```suggestion
  const galaxpaySubscriptionId = webhookSubscription?.myId
  if (!galaxpaySubscriptionId) {
    return res.sendStatus(400)
  }
  const metadataStoreId = webhookSubscription.ExtraFields?.find(metadata => metadata.tagName === 'store_id')
```

2023-03-01 00:20 UTC, leomp12 approved these changes
valeu @wisley7l ✌🏾

2023-03-01 00:22 UTC, merged