feat(webhook ecom): Update subscription with product value/quantity
ecomplus/app-galaxpay pull request #59
Opened 2023-05-24 23:18 UTC by wisley7l

Referente #58

2023-05-26 01:22 UTC, leomp12 requested changes

2023-05-26 01:22 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
> +                  })
Oh eu nem tava lembrando disso 👏🏾

2023-05-26 01:22 UTC, leomp12 commented on functions/routes/galaxpay/webhooks.js
Nesse webhook deles eu não esperava muita alteração na verdade, teve muita alteração nos métodos além dessa troca do `stock_status` dos items?

2023-05-26 01:22 UTC, leomp12 commented on functions/routes/ecom/webhook.js
> +              query += `&&items.sku=${sku}`
```suggestion
              query += `&items.sku=${sku}`
```

2023-05-26 01:22 UTC, leomp12 commented on functions/routes/ecom/webhook.js
> +              query += `&&items.product_id=${resourceId}`
```suggestion
              query += `&items.product_id=${resourceId}`
```

2023-05-26 01:22 UTC, leomp12 commented on functions/ecom.config.js
> +      resource: 'products',
```suggestion
      resource: 'products',
      action: 'change',
```

2023-05-26 01:22 UTC, leomp12 commented on functions/ecom.config.js
> +      resource: 'products',
```suggestion
      resource: 'products',
      action: 'change',
```

2023-05-26 01:22 UTC, leomp12 commented on functions/ecom.config.js
> +      resource: 'products',
```suggestion
      resource: 'products',
      action: 'change',
```

2023-05-26 01:22 UTC, leomp12 commented on functions/lib/store-api/request-api.js
> +  appSdk.apiRequest(storeId, `/orders.json?${query}`, 'GET', null, auth)
Você tá listando todos os pedidos da loja kk
Vai dar bom não

2023-05-26 01:22 UTC, leomp12 commented on functions/lib/store-api/request-api.js
> +  appSdk.apiRequest(storeId, `/orders.json?${query}`, 'GET', null, auth)
Além do `status` que vi em outro lugar, tem que ter dois filtros a mais aqui, um pelo `transactions.app.intermediator.code` ou algum outro field que indique que a transação é do Galaxpay, e outro pra pegar apenas o pedidos iniciais de assinaturas (`transactions.type` ?)

2023-05-26 01:22 UTC, leomp12 commented on functions/routes/ecom/webhook.js
> +                        const product = await getProductsById(appSdk, storeId, item.product_id, auth)
O que foi alterado (`price` ou `quantity`) vai vir no corpo do trigger (`trigger.body`), acho que você não precisa dessa request, ou pelo menos pode tentar evitá-la...

2023-05-26 01:22 UTC, leomp12 commented on functions/routes/ecom/webhook.js
> +                        const item = order.items.find((itemFind) => itemFind.sku === sku || itemFind.product_id === resourceId)
Acho que isso aqui vai dar errado se um pedido tiver duas variações do mesmo produto

2023-05-26 15:06 UTC, wisley7l commented on functions/routes/ecom/modules/create-transaction.js
>    }]
Na vdd esse extrafields nem estão em uso a principio, em uns testes ques estava fzndo aqui que algo não estava dando certo.

2023-05-26 15:10 UTC, wisley7l commented on functions/routes/galaxpay/webhooks.js
Alteração de nome dos métodos 
e internamente o metodo `checkItemsAndRecalculeteOrder` passou a ter mas dois parametros para recalcular o pedido, esse dois paramentros um é o novo item atualizado e um bolleano, para excluir o item caso a quantidade disponivel no estoque seja inferior ao do pedido

2023-05-26 18:05 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +      }
Tá mas isso deveria ser uma config então, não?

2023-06-02 20:34 UTC, leomp12 commented on functions/ecom.config.js
> +    },
Quando muda estoque de variação em seguida corrige o estoque do produto, colocar os dois duplica os webhooks aqui sem necessidade nesse caso

2023-06-02 20:34 UTC, leomp12 commented on functions/ecom.config.js
> +    },
```suggestion
```

2023-06-02 21:39 UTC, leomp12 commented on functions/routes/ecom/webhook.js
> +                              checkItemsAndRecalculeteOrder(order.amount, order.items, plan, newItem, isRemoveItem)
Ideal na verdade era só removermos o item se o estoque for zerado realmente, se a quantidade original é 3 mas só tem 2 faz sentido tentar vender os 2 pelo menos...

2023-06-02 21:39 UTC, leomp12 commented on functions/routes/ecom/webhook.js
> +            const isVariation = trigger.subresource === 'variations'
Isso aqui não vai dar certo pra variação não 🙃

2023-06-02 21:40 UTC, leomp12 commented on functions/routes/ecom/webhook.js
> +            const isVariation = trigger.subresource === 'variations'
Talvez seja melhor você sempre ler o produto todo mesmo e varrer todas as variações se houver

2023-06-02 21:49 UTC, leomp12 reviewed
Sempre ler o produto e percorrer todas as variações, para atualizar o preço use https://developers.e-com.plus/utils/ecomUtils.html#.price :

```js
ecomUtils.price(product)
```
```js
ecomUtils.price({ ...product, ...variation })
```

> Lembrando sempre de adicionar o frete e reduzir o desconto no "novo total"

2023-06-07 01:22 UTC, leomp12 reviewed
Só pra confirmar, chegando webhook de produto estamos:
- [x] (1) Verificando se há alguma assinatura ativa com o produto;
- [x] (2) Lendo o produto atualizado;
- [ ] (3) Percorrendo cada pedido e verificando o item (produto ou variação) pelo SKU no pedido;
- [ ] (4) Se a quantidade do item é menor que o estoque alteramos a quantidade pro próximo pedido da assinatura, evitando zerar (apenas se o estoque for 0);
- [ ] (5) Se o preço do produto for diferente alteramos o preço pro próximo pedido da assinatura;
- [ ] (6) Se não houver alteração nenhuma a assinatura não é atualizada no Galaxpay;
- [x] (7) O pedido original (assinatura) nunca é atualizado na plataforma;
- [x] (8) Os próximos pedidos salvos na plataforma têm quantidades/preços atualizados, não necessariamente iguais aos itens do pedido original;

2023-06-07 01:22 UTC, leomp12 commented on functions/routes/ecom/webhook.js
> +                              const variation = product.variations.find(itemFind => itemFind._id === orderItem.variation_id)
```suggestion
                              const variation = product.variations.find(itemFind => itemFind.sku === orderItem.sku)
```

O ID da variação pode mudar, em geral o SKU é mantido

2023-06-07 01:22 UTC, leomp12 commented on functions/routes/ecom/webhook.js
> +                              }
Se a variação tiver sido removida dá fatal aqui...

2023-06-07 19:06 UTC, wisley7l commented
> Só pra confirmar, chegando webhook de produto estamos:
> - [x] (1) Verificando se há alguma assinatura ativa com o produto;

https://github.com/ecomplus/app-galaxpay/blob/4a829984f2f57796227fef4bf247b7b521e8e873/functions/routes/ecom/webhook.js#L243
Aqui buscamos os pedidos não cancelado que contenha o produto, que são do app_galaxpay e que são do tipo recorrencia. 
Em seguida confirma na API do galaxpay se os pedidos encontrados estão realmente ativos (ou seja que são assinaturas ativas)

> - [x] (2) Lendo o produto atualizado;

https://github.com/ecomplus/app-galaxpay/blob/4a829984f2f57796227fef4bf247b7b521e8e873/functions/routes/ecom/webhook.js#L259

> - [x] (3) Percorrendo cada pedido e verificando o item (produto ou variação) pelo SKU no pedido;

https://github.com/ecomplus/app-galaxpay/blob/4a829984f2f57796227fef4bf247b7b521e8e873/functions/routes/ecom/webhook.js#L255
Aqui percorremos os pedidos (assinaturas ativas no galaxpay)

https://github.com/ecomplus/app-galaxpay/blob/4a829984f2f57796227fef4bf247b7b521e8e873/functions/routes/ecom/webhook.js#L264
Percorremos cada item do pedido e verificamos se tem variação 


> - [x] (4) Se a quantidade do item é menor que o estoque alteramos a quantidade pro próximo pedido da assinatura, evitando zerar (apenas se o estoque for 0);

https://github.com/ecomplus/app-galaxpay/blob/4a829984f2f57796227fef4bf247b7b521e8e873/functions/routes/ecom/webhook.js#L279

https://github.com/ecomplus/app-galaxpay/blob/4a829984f2f57796227fef4bf247b7b521e8e873/functions/routes/ecom/webhook.js#L286

```
 checkItemsAndRecalculeteOrder(order.amount, order.items, docSubscription.plan, newItem)
```

Essa função receberá como parametro o newItem que irá conter quantidade e preço, no qual fará as alterações necessárias no item. 


> - [x] (5) Se o preço do produto for diferente alteramos o preço pro próximo pedido da assinatura;
> - [x] (6) Se não houver alteração nenhuma a assinatura não é atualizada no Galaxpay;

https://github.com/ecomplus/app-galaxpay/blob/42769de3611c9552f634587ba2be42769a0d8ecd/functions/routes/ecom/webhook.js#L292

Se os valores da assinatura for diferente do novo valor calculado os items passam a ser salvos no firestore da assinatura, para verificação, antes de criar o novo pedido e além disso o novo valor é alterado no Galaxpay para criação de novas cobrança

> - [x] (7) O pedido original (assinatura) nunca é atualizado na plataforma;
> - [x] (8) Os próximos pedidos salvos na plataforma têm quantidades/preços atualizados, não necessariamente iguais aos itens do pedido original;
Antes de criar um novo pedido é feito a verificação, para que o novo pedido seja criado com produtos com valores e/ou quantidade corretas.

https://github.com/ecomplus/app-galaxpay/blob/42769de3611c9552f634587ba2be42769a0d8ecd/functions/routes/galaxpay/webhooks.js#L114

2023-06-07 20:09 UTC, leomp12 approved these changes
vamo dale então nelson 👍🏾

2023-06-07 20:10 UTC, merged